---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zoneminder-config
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: freenas-nfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zoneminder-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: freenas-nfs
